"""empty message

Revision ID: 0552a8eda419
Revises: 392a06e7331b
Create Date: 2021-11-26 15:49:53.551188

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0552a8eda419'
down_revision = '392a06e7331b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_model', sa.Column('create_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_model', 'create_on')
    # ### end Alembic commands ###
