"""Add new field photo_url in subscription model, think to use with cloudinary

Revision ID: 07b7fb3ce87d
Revises: 6c3813f8df23
Create Date: 2021-12-03 13:27:26.265776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07b7fb3ce87d'
down_revision = '6c3813f8df23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('photo_url', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'photo_url')
    # ### end Alembic commands ###
