"""Change subscribe model, add photo_ext

Revision ID: 21747fb5bb20
Revises: cddb1424235b
Create Date: 2021-12-19 10:55:55.378419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21747fb5bb20'
down_revision = 'cddb1424235b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscription', sa.Column('photo_ext', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscription', 'photo_ext')
    # ### end Alembic commands ###
