"""Add new table pay type in which save pay type: cash, card, wise, stripe

Revision ID: 29128332c534
Revises: 6a71cc5169f4
Create Date: 2021-12-08 12:17:36.810748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29128332c534'
down_revision = '6a71cc5169f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pay_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('transaction', sa.Column('pay_type', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transaction', 'pay_type', ['pay_type'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transaction', type_='foreignkey')
    op.drop_column('transaction', 'pay_type')
    op.drop_table('pay_type')
    # ### end Alembic commands ###
