"""empty message

Revision ID: 392a06e7331b
Revises: b139057fe3e1
Create Date: 2021-11-25 16:57:24.820258

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392a06e7331b'
down_revision = 'b139057fe3e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tariftype', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tariftype', type_='unique')
    # ### end Alembic commands ###
