"""empty message

Revision ID: 550b1d317d41
Revises: 
Create Date: 2021-11-25 16:38:04.146096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '550b1d317d41'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('capacity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('park',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card', sa.String(length=20), nullable=False),
    sa.Column('tarif_id', sa.String(length=10), nullable=False),
    sa.Column('income', sa.DateTime(), nullable=True),
    sa.Column('outcome', sa.DateTime(), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pay', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tariftype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Enum('common', 'vip', name='tariftypeenum'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=250), nullable=False),
    sa.Column('type', sa.Enum('staff', 'admin', name='usertype'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('subscription',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=32), nullable=True),
    sa.Column('tar_type_id', sa.Integer(), nullable=False),
    sa.Column('active_date_from', sa.DateTime(), nullable=False),
    sa.Column('active_date_to', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tar_type_id'], ['tariftype.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card'),
    sa.UniqueConstraint('email')
    )
    op.create_table('tarif_el',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tarif_id', sa.Integer(), nullable=False),
    sa.Column('stay', sa.String(length=5), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['tarif_id'], ['tariftype.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tarif_el')
    op.drop_table('subscription')
    op.drop_table('user_model')
    op.drop_table('tariftype')
    op.drop_table('park')
    op.drop_table('capacity')
    # ### end Alembic commands ###
