"""Add otc table, use auth from auth manager to integrate with current user

Revision ID: 95f15073e893
Revises: 0552a8eda419
Create Date: 2021-11-29 14:37:15.388091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '95f15073e893'
down_revision = '0552a8eda419'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_park_card'), 'park', ['card'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_park_card'), table_name='park')
    # ### end Alembic commands ###
