"""empty message

Revision ID: b139057fe3e1
Revises: 550b1d317d41
Create Date: 2021-11-25 16:41:06.638094

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b139057fe3e1'
down_revision = '550b1d317d41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tariftype', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tariftype', 'created_on')
    # ### end Alembic commands ###
