"""Add field created_on in OtcModel

Revision ID: b617ced24fdf
Revises: b986a61de65c
Create Date: 2021-12-10 14:28:41.533505

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b617ced24fdf'
down_revision = 'b986a61de65c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('otc', sa.Column('created_on', sa.DateTime(), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('otc', 'created_on')
    # ### end Alembic commands ###
