"""Change some model user and pay_type to use helper function that strip unique field

Revision ID: b986a61de65c
Revises: 29128332c534
Create Date: 2021-12-08 19:10:55.573019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b986a61de65c'
down_revision = '29128332c534'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'pay_type', ['name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'pay_type', type_='unique')
    # ### end Alembic commands ###
